### ISSUE TITLE
Exception in ode

### ISSUE THREAD

**Issue by idontgetoutmuch** [mstksg/hamilton#1]
```
*Main> last $ take 700 $ zipWith (+) (map (pe twoBody) positions) (map (keP twoBody) evolution')
*** Exception: ode: code 349196480
CallStack (from HasCallStack):
  error, called at src/Internal/Devel.hs:51:21 in hmatrix-0.18.0.0-7aYEqJARQEvKYNyM4UGAPZ:Internal.Devel
```

**Comment by mstksg** [comment]
hm, which example is this from?  can you paste the entire code?

**Comment by idontgetoutmuch** [comment]
That is the entire code. I loaded up https://github.com/mstksg/inCode/blob/master/code-samples/hamilton/TwoBody.hs and ran the above at the command line.

**Comment by mstksg** [comment]
Hm, I can't seem to reproduce :/  My result is a list of 700 `-4.5454911`'s in a row.  I actually fixed a compile error in the file (which I just pushed), but I'm assuming you were able to fix it too.

Do you get the same result when you use a smaller number of items to generate?

**Comment by mstksg** [comment]
Steps I'm trying:

~~~
$ stack ghci --package hamilton hmatrix
ghci> :l TwoBody.hs
ghci> last $ take 700 $ zipWith (+) (map (pe twoBody) positions) (map (keP twoBody) evolution')
-4.545391110059894
~~~

**Comment by idontgetoutmuch** [comment]
Curses! I knew I shouldn't have shut down my session. Identical values for the energy sounds very dodgy even if you were using a symplectic integrator you would expect the energy to vary a bit.

Lol - now I can't reproduce either but I get increasing energy as I would expect:

```
*Main> let xs =  take 2000 $ zipWith (+) (map (pe twoBody) positions) (map (keP twoBody) evolution') in take 2 $ map (+ (negate $ head xs)) xs
[0.0,2.0315127358117024e-10]

*Main> let xs =  take 1000 $ zipWith (+) (map (pe twoBody) positions) (map (keP twoBody) evolution') in last $ map (+ (negate $ head xs)) xs
9.112500420282998e-5

*Main> let xs =  take 2000 $ zipWith (+) (map (pe twoBody) positions) (map (keP twoBody) evolution') in last $ map (+ (negate $ head xs)) xs
1.8141323763565254e-4
```

Perhaps we should close this although it is worrying I got an exception.

**Comment by mstksg** [comment]
Indeed, it does vary :)

It's a bit worrying, but it seems like it might be a problem on *hmatrix* or *hmatrix-gsl*'s end.  Let me know if you're able to reproduce it and I'll try to track down the cause.

For the record though, I have had some experiences with nondeterministic crashes in hmatrix that happen intermittently when working with it in my other projects.  I've never been able to figure out what the problem with those were, but this might be related?

**Comment by idontgetoutmuch** [comment]
I have a vague recollection that @bitonic fixed something to do with `unsafePerformIO` in `hmatrix` recently but maybe this is unrelated and / or his fix hasn't yet made it into a hackage release.

**Comment by bitonic** [comment]
I didn't read this ticket, but for reference, https://github.com/albertoruiz/hmatrix/issues/198 is the bug @idontgetoutmuch is referring to.

**Comment by idontgetoutmuch** [comment]
Thanks but sadly I think this is a different problem as I am using a version of `hmatrix` that includes the fix :( I am going to close for now as I cannot reproduce.
