### ISSUE TITLE
hamilton is currently breaking on Stackage

### ISSUE THREAD

**Issue by cdornan** [mstksg/hamilton#4]
`hamilton` is currently breaking on Stackage nightly with the following error and we have suspended it to get the release out. Could you let us know when we can add it back -- cheers.

---

Preprocessing library for hamilton-0.1.0.1..
Building library for hamilton-0.1.0.1..
[1 of 1] Compiling Numeric.Hamilton ( src/Numeric/Hamilton.hs, dist/build/Numeric/Hamilton.o )

src/Numeric/Hamilton.hs:435:26: error:
    • The constructor ‘NLE’ should have 2 arguments, but has been given 1
    • In the pattern: NLE Refl
      In a case alternative:
          NLE Refl -> error "evolveHam': Internal error"
      In the expression:
        case (Proxy %<=? Proxy) :: (2 :<=? s) of
          LE Refl -> (if l1 then tail else id) . toList $ evolveHam s p0 v
          NLE Refl -> error "evolveHam': Internal error"
    |
435 |                          NLE Refl -> error "evolveHam': Internal error"
    |                          ^^^^^^^^

**Comment by mstksg** [comment]
Things should be fixed in *hamilton-0.1.0.2`; thanks for the heads up!
